services:
  eureka-server:
    image: laus1205/eureka-server:1.0.0
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
     - market-system

  gateway-api:
    image: laus1205/gateway-api:1.0.0
    ports:
      - "8765:8765"
    expose:
      - "8765"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - market-system

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - market-system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  

  product-api:
    image: laus1205/product-api:1.0.3
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
      - gateway-api
      - db
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
     - market-system

  sale-api:
    image: laus1205/sale-api:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
      gateway-api:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
     - market-system

  purchase-order-api:
    image: laus1205/purchase-order-api:1.0.0
    ports:
      - "8200:8200"
    depends_on:
      eureka-server:
        condition: service_started
      gateway-api:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
     - market-system     


networks:
  market-system:
    driver: bridge

volumes:
  postgres_data: