spring:
  application:
    name: payroll-api
  datasource:
    url: jdbc:postgresql://localhost:5432/product-api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: ${PORT:8100}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
